---
name: Config-Model-Itself
version: 1.210
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Graphical model editor for Config::Model
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.635
  Config::Model::TkUI: 1.203
  Log::Log4perl: 0
provides:
  Config::Model::Itself:
    file: lib/Config/Model/Itself.pm
    version: 1.210
  Config::Model::Itself::TkEditUI:
    file: lib/Config/Model/Itself/TkEditUI.pm
    version: 1.0615
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
