---
abstract: 'Graphical model editor for Config::Model'
author:
  - 'Dominique Dumont (ddumont at cpan dot org)'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-Itself
provides:
  Config::Model::Itself:
    file: lib/Config/Model/Itself.pm
    version: 1.212
  Config::Model::Itself::TkEditUI:
    file: lib/Config/Model/Itself/TkEditUI.pm
    version: 1.0615
requires:
  Config::Model: 0.643
  Config::Model::TkUI: 1.210
  Log::Log4perl: 0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 1.212
