---
name: Config-Model-Itself
version: 0.201
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: Configuration model editor for Config::Model
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.621
  Log::Log4perl: 0
recommends:
  Config::Model::TkUI: 0
provides:
  Config::Model::Itself:
    file: lib/Config/Model/Itself.pm
    version: 1.0583
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
