---
abstract: 'Model editor for Config::Model'
author:
  - 'Dominique Dumont'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-Itself
requires:
  Config::Model: 1.228
  Config::Model::TkUI: 1.210
  Log::Log4perl: 0
  Pod::POM: 0
  Tk: 0
  YAML::Any: 0
version: 1.221
